/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ypLcNXd0WfB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Toggle } from "@/components/ui/toggle"
import Link from "next/link"
import { CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import { JSX, SVGProps } from "react"

export default function PortfolioCard() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[#f5f5f5] dark:bg-[#1a1b1e] text-[#333] dark:text-[#f5f5f5]">
      <section className="flex flex-col items-center justify-center px-4 py-12 md:py-24 lg:py-32 bg-[#a7aef0] text-center">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Welcome to My Portfolio</h1>
        <p className="mt-6 text-xl leading-8">Discover the work and journey of a passionate developer.</p>
      </section>
      {/* <div className="absolute top-4 right-4 flex items-center">
        <span className="mr-2 text-sm font-medium">Theme:</span>
        <Toggle
          aria-label="Toggle theme"
          className="flex items-center justify-between px-3 py-1 rounded-md text-sm font-medium transition-colors hover:bg-gray-100 dark:hover:bg-gray-800"
          variant="outline"
        >
          <SunIcon className="h-5 w-5 mr-2" />
          <span>Light</span>
          <MoonIcon className="h-5 w-5 ml-2" />
        </Toggle>
      </div> */}
      <section className="py-12 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h2 className="text-3xl font-bold mb-4">About Me</h2>
              <p className="text-lg text leading-relaxed mb-6">
              Hi there! 👋 I&apos;m Ayush a second-year Computer Science Engineering student from Mumbai, gearing up for my third year starting July 2024. With an adventurous spirit and a hunger for learning, I&apos;m excited to explore the endless possibilities that lie ahead in both my personal and professional life.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                I bring a unique perspective to every project I work on. I have a deep passion for software engineering and coding, always eager to tackle new challenges and learn something new.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                Alongside my academic journey, I find joy in playing cricket and embarking on spiritual journeys to shrines.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <Image
                alt="Profile Picture"
                className="rounded-full"
                height={400}
                src="/ayush.jpg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
        </div>
        {/* C/C++, JavaScript, TypeScript, Java, Python, HTML5, CSS3,React.js, Express.js, Hono.js, Vite, Next.js MongoDB, PostgreSQL, Redis, Upstash, Prisma Git, Github, Docker, Node.js, Vscode, Vercel, Cloudflare, IntelliJ IDEA */}
      </section>
      <section className="py-12 md:py-24 lg:py-32 bg-[#f5f5f5] dark:bg-[#1a1b1e]">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="text-3xl font-bold mb-8">My Skills</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-8">
            
            <div className="flex flex-col items-center">
              <Image src="/c++.svg" alt="C++" width="24" height="24" className="h-12 w-12 mb-2 text-[#a7aef0]" />
              <p className="text-lg font-medium">C++</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/javascript.svg" alt="JavaScript" width="24" height="24" className="h-12 w-12 mb-2 text-[#f0db4f]" />
              <p className="text-lg font-medium">JavaScript</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/typescript.svg" alt="TypeScript" width="24" height="24" className="h-12 w-12 mb-2 text-[#3178c6]" />
              <p className="text-lg font-medium">TypeScript</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/java.svg" alt="Java" width="24" height="24" className="h-12 w-12 mb-2 text-[#007396]" />
              <p className="text-lg font-medium">Java</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/python.svg" alt="Python" width="24" height="24" className="h-12 w-12 mb-2 text-[#3776ab]" />
              <p className="text-lg font-medium">Python</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/html5.svg" alt="HTML5" width="24" height="24" className="h-12 w-12 mb-2 text-[#e34f26]" />
              <p className="text-lg font-medium">HTML5</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/css3.svg" alt="CSS3" width="24" height="24" className="h-12 w-12 mb-2 text-[#1572b6]" />
              <p className="text-lg font-medium">CSS3</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/react.svg" alt="React.js" width="24" height="24" className="h-12 w-12 mb-2 text-[#61dafb]" />
              <p className="text-lg font-medium">React.js</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/express.svg" alt="Express.js" width="24" height="24" className="h-12 w-12 mb-2 text-[#000000]" />
              <p className="text-lg font-medium">Express.js</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/hono.svg" alt="Hono.js" width="24" height="24" className="h-12 w-12 mb-2 text-[#ffd700]" />
              <p className="text-lg font-medium">Hono.js</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/vite.svg" alt="Vite" width="24" height="24" className="h-12 w-12 mb-2 text-[#646cff]" />
              <p className="text-lg font-medium">Vite</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/nextjs.svg" alt="Next.js" width="24" height="24" className="h-12 w-12 mb-2 text-[#000000]" />
              <p className="text-lg font-medium">Next.js</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/mongodb.svg" alt="MongoDB" width="24" height="24" className="h-12 w-12 mb-2 text-[#47a248]" />
              <p className="text-lg font-medium">MongoDB</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/postgresql.svg" alt="PostgreSQL" width="24" height="24" className="h-12 w-12 mb-2 text-[#336791]" />
              <p className="text-lg font-medium">PostgreSQL</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/redis.svg" alt="Redis" width="24" height="24" className="h-12 w-12 mb-2 text-[#dc382d]" />
              <p className="text-lg font-medium">Redis</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/upstash.svg" alt="Upstash" width="24" height="24" className="h-12 w-12 mb-2 text-[#4c4c4c]" />
              <p className="text-lg font-medium">Upstash</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/prisma.svg" alt="Prisma" width="24" height="24" className="h-12 w-12 mb-2 text-[#2d3748]" />
              <p className="text-lg font-medium">Prisma</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/git.svg" alt="Git" width="24" height="24" className="h-12 w-12 mb-2 text-[#f05032]" />
              <p className="text-lg font-medium">Git</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/github.svg" alt="Github" width="24" height="24" className="h-12 w-12 mb-2 text-[#181717]" />
              <p className="text-lg font-medium">Github</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/docker.svg" alt="Docker" width="24" height="24" className="h-12 w-12 mb-2 text-[#2496ed]" />
              <p className="text-lg font-medium">Docker</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/nodejs.svg" alt="Node.js" width="24" height="24" className="h-12 w-12 mb-2 text-[#339933]" />
              <p className="text-lg font-medium">Node.js</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/vscode.svg" alt="Vscode" width="244" height="244" className="h-12 w-12 mb-2 text-[#007acc]" />
              <p className="text-lg font-medium">Vscode</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/vercel.svg" alt="Vercel" width="24" height="24" className="h-12 w-12 mb-2 text-[#000000]" />
              <p className="text-lg font-medium">Vercel</p>
            </div>

            <div className="flex flex-col items-center">
              <Image src="/cloudflare.svg" alt="Cloudflare" width="24" height="24" className="h-12 w-12 mb-2 text-[#f38020]" />
              <p className="text-lg font-medium">Cloudflare</p>
            </div>

          </div>
        </div>
      </section>
      <section className="py-12 md:py-24 lg:py-32 bg-[#f5f5f5] dark:bg-[#1a1b1e]">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="text-3xl font-bold mb-8">My Projects</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card>
              <CardContent className="flex flex-col items-center justify-center p-8">
                <Image
                  alt="Project 1"
                  className="rounded-lg mb-4"
                  height={250}
                  src="/speedsearch.png"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <h3 className="text-2xl font-bold mb-2 text-[#a7aef0]">SpeedSearch</h3>
                <p className="text-lg leading-relaxed mb-4 line-clamp-5 text-center">SpeedSearch is a hybrid search engine web application designed to facilitate semantic search capabilities using Next.js. By implementing a highly efficient search engine powered by Postgres and utilizing Upstash as a scalable vector database, SpeedSearch stores and retrieves vector embeddings effectively. The application integrates Drizzle ORM for seamless interaction with the Postgres database, ensuring robust and type-safe queries. Additionally, OpenAI&apos;s vector embedding API is employed to transform and index textual data into high-dimensional vectors, enhancing the search functionality with AI-powered relevance and accuracy. This sophisticated setup ensures users experience fast and accurate search results. Visit speedsearch.ayush.dev for more details.</p>
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-[#a7aef0] px-4 py-2 text-sm font-medium text-[#f5f5f5] shadow transition-colors hover:bg-[#8c94d6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#a7aef0] disabled:pointer-events-none disabled:opacity-50"
                  href="#"
                >
                  View Project
                </Link>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col items-center justify-center p-8">
                <Image
                  alt="Project 2"
                  className="rounded-lg mb-4"
                  height={250}
                  src="/fastapi.png"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <h3 className="text-2xl font-bold mb-2 text-[#a7aef0]">FastAPI</h3>
                <p className=" text-lg leading-relaxed mb-4 line-clamp-5 text-center">FastAPI is a high-performance, globally distributed API designed with Hono, a lightweight web framework aimed at minimal overhead and rapid response times. The API is deployed using serverless functions via Cloudflare Workers, ensuring low latency and high availability through global distribution. Redis is utilized as a fast, in-memory database for efficient data storage and caching, significantly improving data retrieval speeds and overall performance. Cloudflare Workers&apos; edge network capabilities are harnessed to deliver API responses swiftly and efficiently to users around the world. Explore the project at fastapi.ayush.dev.</p>
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-[#a7aef0] px-4 py-2 text-sm font-medium text-[#f5f5f5] shadow transition-colors hover:bg-[#8c94d6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#a7aef0] disabled:pointer-events-none disabled:opacity-50"
                  href="#"
                >
                  View Project
                </Link>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col items-center justify-center p-8">
                <Image
                  alt="Project 3"
                  className="rounded-lg mb-4"
                  height={250}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <h3 className="text-2xl font-bold mb-2 text-[#a7aef0]">Full Stack Booking Software</h3>
                <p className="text-lg leading-relaxed mb-4 line-clamp-5 text-center">This full-stack booking software is crafted for restaurants, utilizing Next.js to provide a seamless and responsive user experience. Prisma ORM is integrated for robust database management and streamlined data operations, ensuring high performance and scalability. TailwindCSS is used to style the application, offering a modern and responsive design that enhances the user interface. The software also employs tRPC for end-to-end type safety and efficient API communication, eliminating the need for manual API client generation. Real-time booking updates and notifications are implemented to ensure smooth reservation management for both customers and restaurant staff. Check out book.ayush.dev for more information.</p>
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-[#a7aef0] px-4 py-2 text-sm font-medium text-[#f5f5f5] shadow transition-colors hover:bg-[#8c94d6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#a7aef0] disabled:pointer-events-none disabled:opacity-50"
                  href="#"
                >
                  View Project
                </Link>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col items-center justify-center p-8">
                <Image
                  alt="Project 3"
                  className="rounded-lg mb-4"
                  height={250}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/250",
                    objectFit: "cover",
                  }}
                  width={400}
                />
                <h3 className="text-2xl font-bold mb-2 text-[#a7aef0]">PhishEYES</h3>
                <p className="text-lg leading-relaxed mb-4 line-clamp-5 text-center">PhishEYES is a full-stack phishing prevention application in development, leveraging React.js to analyze websites and prevent attacks. The project integrates natural language processing (NLP) to analyze domain names and website DOM content for any suspicious activity, providing a probability score based on backend code and content similarity. A web crawler is being developed to monitor website content continuously. Additionally, a report download system is created to generate detailed website reports. OpenCV integration is also underway to analyze web screenshots against actual website appearances. This tool aims to offer comprehensive protection against phishing threats. More details can be found on the project&apos;s GitHub.</p>
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-[#a7aef0] px-4 py-2 text-sm font-medium text-[#f5f5f5] shadow transition-colors hover:bg-[#8c94d6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#a7aef0] disabled:pointer-events-none disabled:opacity-50"
                  href="#"
                >
                  View Project
                </Link>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="text-3xl font-bold mb-8">Get in Touch</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <p className="text-lg leading-relaxed mb-6">
                I&lsquo;d love to hear from you! Feel free to reach out to me using the following contact information:
              </p>
              <div className="space-y-4">
                <div className="flex items-center">
                  <InboxIcon className="mr-4 h-6 w-6 text-[#a7aef0]" />
                  <a className="text-lg hover:underline" href="#">
                    ayushmaurya2468@gmail.com
                  </a>
                </div>
                <div className="flex items-center">
                  <PhoneIcon className="mr-4 h-6 w-6 text-[#a7aef0]" />
                  <a className="text-lg hover:underline" href="#">
                    +91 72086 52578
                  </a>
                </div>
                <div className="flex items-center">
                  <LinkedinIcon className="mr-4 h-6 w-6 text-[#a7aef0]" />
                  <a className="text-lg hover:underline" href="https://www.linkedin.com/in/ayush-maurya-1762a3238" target="_blank">
                    LinkedIn
                  </a>
                </div>
                <div className="flex items-center">
                  <GithubIcon className="mr-4 h-6 w-6 text-[#a7aef0]" />
                  <a className="text-lg hover:underline" href="https://www.github.com/maurya-ayush" target="_blank">
                    Github
                  </a>
                </div>
              </div>
            </div>
            <div>
              <form className="space-y-4">
                <Input
                  className="w-full rounded-md border border-gray-200 px-4 py-2 text-lg focus:border-[#a7aef0] focus:outline-none dark:bg-[#1a1b1e] dark:text-[#f5f5f5] dark:border-gray-700"
                  placeholder="Name"
                  type="text"
                />
                <Input
                  className="w-full rounded-md border border-gray-200 px-4 py-2 text-lg focus:border-[#a7aef0] focus:outline-none dark:bg-[#1a1b1e] dark:text-[#f5f5f5] dark:border-gray-700"
                  placeholder="Email"
                  type="email"
                />
                <Textarea
                  className="w-full rounded-md border border-gray-200 px-4 py-2 text-lg focus:border-[#a7aef0] focus:outline-none dark:bg-[#1a1b1e] dark:text-[#f5f5f5] dark:border-gray-700"
                  placeholder="Message"
                />
                <Button
                  className="inline-flex items-center justify-center rounded-md bg-[#a7aef0] px-4 py-2 text-sm font-medium text-[#f5f5f5] shadow transition-colors hover:bg-[#8c94d6] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#a7aef0] disabled:pointer-events-none disabled:opacity-50"
                  type="submit"
                >
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </div>
      </section>
      <footer className="bg-[#a7aef0] py-6 text-center">
        <p className="text-lg">© 2024 Ayush Maurya. All rights reserved.</p>
      </footer>
    </div>
  )
}

function InboxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />
      <path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
    </svg>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}

function PhoneIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.167 6.839 9.489.5.092.683-.217.683-.482 0-.237-.009-.868-.014-1.703-2.782.604-3.369-1.342-3.369-1.342-.454-1.156-1.11-1.465-1.11-1.465-.909-.621.069-.608.069-.608 1.004.07 1.531 1.032 1.531 1.032.892 1.529 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.252-4.555-1.111-4.555-4.944 0-1.092.39-1.986 1.029-2.685-.103-.253-.446-1.27.098-2.645 0 0 .84-.269 2.75 1.026A9.563 9.563 0 0112 6.801c.852.004 1.709.115 2.51.337 1.909-1.296 2.748-1.026 2.748-1.026.546 1.375.203 2.392.1 2.645.64.699 1.027 1.593 1.027 2.685 0 3.842-2.339 4.687-4.566 4.936.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.748 0 .267.18.577.688.478C19.136 20.162 22 16.418 22 12c0-5.523-4.477-10-10-10z"></path>
    </svg>
  )
}